client_1:
  train:
    optimizer:
      lr: 0.01
  eval:
    base: 0.86
client_2:
  train:
    optimizer:
      lr: 0.001
  eval:
    base: 0.823
client_3:
  train:
    optimizer:
      lr: 0.1
  eval:
    base: 0.830
client_4:
  train:
    optimizer:
      lr: 0.1
  eval:
    base: 0.667
client_5:
  train:
    optimizer:
      lr: 0.1
  eval:
    base: 0.541
client_6:
  train:
    optimizer:
      lr: 0.1
  eval:
    base: 0.853
client_7:
  train:
    optimizer:
      lr: 0.1
  eval:
    base: 0.531
client_8:
  train:
    optimizer:
      lr: 0.1
  eval:
    base: 0.663
client_9:
  train:
    optimizer:
      lr: 0.05
  eval:
    base: 0.567
client_10:
  train:
    optimizer:
      lr: 0.001
  eval:
    base: 0.657
client_11:
  train:
    optimizer:
      lr: 0.05
  eval:
    base: 0.709
client_12:
  train:
    optimizer:
      lr: 0.01
  eval:
    base: 0.985
client_13:
  train:
    optimizer:
      lr: 0.005
  eval:
    base: 0.703
