use_gpu: True
device: 0
early_stop:
  patience: 200
  improve_indicator_mode: mean
  the_smaller_the_better: False
federate:
  method: 'Graph-DC-FedBN'
  mode: 'standalone'
  make_global_eval: False
  total_round_num: 400
  share_local_model: False
train:
  local_update_steps: 1
  batch_or_epoch: 'epoch'
  optimizer:
    lr: 0.01
    weight_decay: 0.0005
    type: SGD
data:
  root: data/
  type: fs_contest_data
  splitter: ooxx
model:
  dropout: 0.
  type: gin
  hidden: 64
  out_channels: 0
  task: graphClassification
personalization:
  local_param: [ 'encoder_atom', 'encoder', 'clf', 'norms' ]  # pre, post + FedBN

criterion:
  type: CrossEntropyLoss
trainer:
  type: graphminibatch_trainer
#finetune:
#  before_eval: False
  # local_update_steps: 0
eval:
  freq: 1
  metrics: ['imp_ratio', 'acc']
  report: ['avg']
  best_res_update_round_wise_key: val_imp_ratio
  count_flops: False
  base: 0.