use_gpu: True
device: 0
early_stop:
  patience: 300
  improve_indicator_mode: mean
  the_smaller_the_better: False
federate:
  method: 'Graph-DT-FedBN'
  mode: 'standalone'
  make_global_eval: False
  total_round_num: 400
  share_local_model: False
train:
  local_update_steps: 1
  batch_or_epoch: 'epoch'
  optimizer:
    lr: 0.5
    weight_decay: 0.0005
    type: SGD
grad:
  grad_clip: 5
data:
  root: data/
  type: graph-dt
  splitter: ooxx
model:
  type: gin
  hidden: 64
  out_channels: 0
  task: graph
  dropout: 0.
personalization:
  local_param: ['encoder_atom', 'encoder', 'clf', 'norms']   # to handle size-different pre & post layers

criterion:
  type: CrossEntropyLoss
trainer:
  type: graphminibatch_trainer
eval:
  freq: 1
  metrics: ['imp_ratio']
  report: ['avg']
  best_res_update_round_wise_key: val_imp_ratio
  count_flops: False
  base: 0.