client_1:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 1 #60
    optimizer:
      lr: 0.01
  eval:
    metrics: ['acc', 'imp_ratio']
    base: 0.263789
  params:
    alpha: 0.1
client_2:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 1 #32
    optimizer:
      lr: 0.001
  eval:
    metrics: ['acc', 'imp_ratio']
    base: 0.289617
  params:
      alpha: 0.1
client_3:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 8
    optimizer:
      lr: 0.01
  eval:
    metrics: ['acc', 'imp_ratio']
    base: 0.355404
  params:
    alpha: 0.1
client_4:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 166
    optimizer:
      lr: 0.001
  eval:
    metrics: ['acc', 'imp_ratio']
    base: 0.176471
  params:
    alpha: 0.1
client_5:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 54
    optimizer:
      lr: 0.01
  eval:
    metrics: ['acc', 'imp_ratio']
    base: 0.396825
  params:
    alpha: 0.1
client_6:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 60
    optimizer:
      lr: 0.001
  eval:
    metrics: ['acc', 'imp_ratio']
    base: 0.261580
  params:
    alpha: 0.1
client_7:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 60
    optimizer:
      lr: 0.001
  eval:
    metrics: ['acc', 'imp_ratio']
    base: 0.302378
  params:
    alpha: 0.1
client_8:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 6
    optimizer:
      lr: 0.1
  eval:
    metrics: ['acc', 'imp_ratio']
    base: 0.211538
  params:
    alpha: 0.1
client_9:
  model:
    out_channels: 1
    task: graphRegression
  criterion:
    type: MSELoss
  train:
    optimizer:
      lr: 0.1
  eval:
    base: 0.059199
  params:
    alpha: 0.1
client_10:
  model:
    out_channels: 10
    task: graphRegression
  criterion:
    type: MSELoss
  train:
    local_update_steps: 1
    optimizer:
      lr: 0.05
  eval:
    base: 0.007083
  params:
    alpha: 0.1
client_11:
  model:
    out_channels: 1
    task: graphRegression
  criterion:
    type: MSELoss
  train:
    local_update_steps: 30
    optimizer:
      lr: 0.01
  eval:
    base: 0.734011
  params:
    alpha: 0.1
client_12:
  model:
    out_channels: 1
    task: graphRegression
  criterion:
    type: MSELoss
  train:
    local_update_steps: 100
    optimizer:
      lr: 0.001
  eval:
    base: 1.361326
  params:
    alpha: 0.1
client_13:
  model:
    out_channels: 12
    task: graphRegression
  criterion:
    type: MSELoss
  train:
    local_update_steps: 1
    optimizer:
      lr: 0.1
  eval:
    base: 0.004389
  params:
    alpha: 0.1